services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    env_file: "env/.user.env"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
